// ============================================================
// BCC Rules Quiz — Quiz Data File
// To create a new quiz, copy this file, update QUIZ_CONFIG,
// and place it alongside quiz-template.html as index.html
// ============================================================

const QUIZ_CONFIG = {
  title:      "Beltway Cricket Community Rules Quiz",
  subtitle:   "Test your knowledge of the BCC Rule Book.",
  linkText:   "BCC Rule Book",
  linkUrl:    "https://docs.google.com/document/d/1TQzDJw0btwcZ_Pmzb8CubpN1rHnaN-Kk",

  // Each question:
  //   s   : category name (must match an entry in CATEGORIES)
  //   q   : question text
  //   opts: array of 4 answer strings
  //   ans : index (0-3) of the correct answer
  //   ex  : explanation shown after answering
  questions: [
    { s:'Wide Balls', q:'A striker attempts a switch hit. The ball passes outside the wide line mark on his original off side. What is the correct call?', opts:['Automatically called a wide, since the ball is outside the off-side wide line mark','Not a wide, because the batter changed stance',"The umpire's judgment call whether it is a wide",'Called a no ball for dangerous bowling'], ans:2, ex:"Rule 6.3: For a switch hit, wide ball is judged based on both wide line marks. If the ball goes outside the original off-side wide line mark, it is the umpire's judgment call." },
    { s:'Wide Balls', q:'A striker attempts a switch hit. The ball goes outside his original leg stump but stays inside the wide line mark on his original leg side. What is the call?', opts:["Wide, because the ball passed the batter's new leg stump","Not a wide","Wide, because the batter moved","Dead ball, because a switch hit is not permitted"], ans:1, ex:'Rule 6.3: If the ball goes outside the original leg stump but is inside the wide line mark on the original leg side, it shall NOT be judged as a wide ball.' },
    { s:'No Ball', q:'A bowler delivers the ball from behind the bowling crease (non-striker stump line). What is the correct call?', opts:['No ball — bowler must deliver from behind the popping crease only','No ball — the delivery must pass over the popping crease','Not a no ball — bowling from behind the bowling crease is permitted','Dead ball — the umpire must warn the bowler'], ans:2, ex:'Rule 7.1.3: Bowlers may bowl from behind the bowling crease (non-striker stump line). This is not a No Ball.' },
    { s:'No Ball', q:'A batter steps outside the popping crease to hit a ball. The umpire believes the full toss would have been above waist height had the batter stayed at the crease. What should be called?', opts:['Not a no ball — the batter moved, so the height check does not apply','Wide ball, because the batter moved forward','No ball — the umpire approximates where it would have passed if the batter stood at the crease, and no balls cannot be denied because the batter stepped out','Dead ball — the batter should not have left the crease'], ans:2, ex:'Rule 7.2.1: The leg umpire should approximate where the ball would have passed had the batter been at the popping crease. No balls cannot be denied simply because a batsman stepped outside the crease.' },
    { s:'No Ball', q:"In the same over, a bowler has already received an official warning for a bouncer between the striker's shoulder and the top of the head. He bowls a second such bouncer in the same over. What is the call?", opts:['Wide ball','No ball','Dead ball with another warning','Legal delivery — one bouncer per over is a guideline only'], ans:1, ex:'Rule 7.2.2: One bouncer between shoulder and top of head is allowed per over, but the umpire must give a warning. A second such bouncer in the same over after the warning is a No Ball.' },
    { s:'No Ball', q:"A ball is bowled and passes above the striker's head height (standing upright at the popping crease) without bouncing. It is NOT the second bouncer of the over. What is the correct call?", opts:['No ball','Wide','Dead ball','Legal delivery — height only matters for full tosses'], ans:1, ex:'Rule 7.2.4: Any ball passing above head height should be called a Wide (not a No Ball), unless it is the second bouncer of the over (in which case it is a No Ball).' },
    { s:'No Ball', q:"A ball passes above the striker's head height but the batter swings and makes contact. What is the call?", opts:['Wide — the ball was above head height regardless of bat contact','No ball — any ball above head height is a no ball','Not a wide — the batter hit the ball, so it is treated as a legal delivery (bouncer)','Dead ball — the ball was too dangerous'], ans:2, ex:'Rule 7.2.5: If the batsman hits such a ball, it is not called a wide — it will be considered a bouncer.' },
    { s:'No Ball', q:"The leg umpire calls 'Wide' first, and moments later the main umpire calls 'No Ball' for the same delivery. What is the correct outcome?", opts:['Wide stands — the first call wins','Both Wide and No Ball are counted, adding to extras','No Ball overrides — the Wide call is revoked and No Ball is counted','Dead ball — conflicting calls cancel each other out'], ans:2, ex:'Rule 7.2.6: A call for No Ball will override a call for a Wide ball. Even if the No Ball call comes after the Wide call, the No Ball should be counted and the Wide call revoked.' },
    { s:'No Ball', q:"During his delivery stride, a bowler accidentally breaks the non-striker's end stumps and then delivers the ball. What should be called?", opts:['Dead ball — the ball cannot be bowled once stumps are broken','No ball','Legal delivery — breaking stumps in the stride is a common occurrence','Wide ball — it is an irregular action'], ans:1, ex:"Rule 7.3.1: If a bowler breaks the non-striker's end stumps in the delivery stride and then delivers the ball, it should be called a No Ball." },
    { s:'No Ball', q:'A fielder on the ground makes audible noise after the bowler starts his run-up. It is the first such occurrence in the match. What should happen?', opts:['No ball immediately — any fielder noise after run-up starts is a no ball','Warning to the entire team; a no ball is called only on a subsequent offence','Dead ball — play must be restarted','Penalty runs awarded to the batting team'], ans:1, ex:'Rule 7.3.4: The ball should be called a No Ball after 1 warning to the entire team. The first offence earns a warning; a No Ball follows if it happens again.' },
    { s:'No Ball', q:'The fielding captain places 6 fielders on the leg side. The ball is bowled. What is the call?', opts:['Legal — there is no limit on leg-side fielders','No ball — more than 5 fielders on the leg side is not permitted','Wide — unusual field placement leads to a wide call','Dead ball — the umpire must first instruct the captain to rearrange the field'], ans:1, ex:'Rule 7.3.5: If more than 5 fielders are fielding on the leg side, the ball should be called a No Ball. There is no limit on fielders on the off side.' },
    { s:'No Ball', q:'During a non-power play over, the fielding team has 6 fielders outside the inner circle at the time the ball is bowled. What is the call?', opts:['Legal — fielder restrictions only apply during power plays','No ball','Wide ball','Dead ball with a team warning'], ans:1, ex:'Rule 7.3.7: If more than 5 fielders are placed outside the inner circle during non-power play overs at the time a ball is bowled, the ball should be called a No Ball.' },
    { s:'No Ball', q:'After the bowler commences his run-up, the wicketkeeper makes a significant lateral (sideways) movement before the ball reaches the striker. What should be called?', opts:['Legal — keepers are free to reposition at any time','Wide ball — the movement unsettles the batter','No ball','Dead ball — the over must be restarted'], ans:2, ex:'Rule 7.3.8: The wicketkeeper is not allowed to make significant lateral movement after the bowler starts his run-up. If the umpire determines this occurred, the delivery shall be declared a No Ball.' },
    { s:'No Ball', q:'A bowler delivers the ball underarm along the ground. What is the call?', opts:['Legal — underarm bowling is permitted in BCC','Wide ball','Dead ball','No ball'], ans:3, ex:'Rule 7.3.13: Underarm bowling should be considered a No Ball.' },
    { s:'Dead Ball', q:'A ball bounces twice before reaching the stumps. It is not a No Ball or a Wide. What should be called?', opts:['No ball — double-bounce balls are always no balls','Wide ball','Dead ball','Legal delivery — the batter may still hit it'], ans:2, ex:'Rule 8.1.1: A ball that bounces two or more times before reaching the stumps shall be considered a Dead Ball, unless it qualifies as a No Ball or a Wide.' },
    { s:'Penalty Runs', q:"While attempting a run out, the fielder's throw hits a water bottle on the pitch and then strikes the stumps, with the batsman short of his crease. What is the correct decision?", opts:['Not out — the ball hitting the water bottle voids the dismissal','5 penalty runs to the batting team; batsman is not out','Run out — the batsman should be given out','Dead ball — a foreign object on the pitch cancels the play'], ans:2, ex:'Rule 9.2: If the ball hits a passive object first and then hits the stumps with the batsman short of his crease, the batsman should be given run out. The passive object does not protect the batsman.' },
  ]
};
